services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
    ports:
      - "3306:3306"
